[package]
name = "jrni"
version = "0.1.0"
authors = ["James O'Beirne <james.obeirne@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
threadpool = "1.7.1"
num_cpus = "1.9.0"
walkdir = "2.2.7"
dirs = "1.0.4"
serde = "1.0.83"
serde_yaml = "0.8.8"
chrono = "0.4.6"
error-chain = "0.12.0"
